### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by hoangnatalie** [hoangnatalie/github-flow-assignment#1]
**User Story**
As a student, I need to know if I am passing all my classes. So, I want to view my grades online in order to make sure that I am doing good in all my classes.

**Tasks**
- [x] create a model for grades.
- [x] create a model for specific assignments
- [x] create a UI for students to view all their grades.

**Acceptance Criteria**
* only works on Chrome
* students will only be able to check their own grades

**Acceptance Test**
1. students are able to view their grades
2. students is able to see their gpa
3. students will be sent a notification when grades are updated

**Comment by eyu776** [comment]
> **User Story** As a student, I need to know if I am passing all my classes. So, I want to view my grades online in order to make sure that I am doing good in all my classes.
> 
> **Tasks**
> 
> * [x]  create a model for grades.
> * [x]  create a model for specific assignments
> * [x]  create a UI for students to view all their grades.
> 
> **Acceptance Criteria** *only works on Chrome *students will only be able to check their own grades
> 
> **Acceptance Test**
> 
> 1. students are able to view their grades
> 2. students is able to see their gpa
> 3. students will be sent a notification when grades are updated

to create an unordered list in markdown use
```
* {content}
* {content}
* {content}
```

e.g.
* works on Chrome
* students will only be able to check their own grades

**Comment by hoangnatalie** [comment]
> > **User Story** As a student, I need to know if I am passing all my classes. So, I want to view my grades online in order to make sure that I am doing good in all my classes.
> > 
> > **Tasks**
> > 
> > * [x]  create a model for grades.
> > * [x]  create a model for specific assignments
> > * [x]  create a UI for students to view all their grades.
> > 
> > **Acceptance Criteria** *only works on Chrome *students will only be able to check their own grades
> > 
> > **Acceptance Test**
> > 
> > 1. students are able to view their grades
> > 2. students is able to see their gpa
> > 3. students will be sent a notification when grades are updated
> 
> to create an unordered list in markdown use
> ```
> * {content}
> * {content}
> * {content}
> ```
> 
> e.g.
> * works on Chrome
> * students will only be able to check their own grades

Thank you!
